//tag::ref-doc[]
= FTP Sink 

FTP sink is a simple option to push files to an FTP server from incoming messages.

It uses an `ftp-outbound-adapter`, therefore incoming messages could be either a `java.io.File` object, a `String` (content of the file)
or an array of `bytes` (file content as well).

To use this sink, you need a username and a password to login.

NOTE: By default Spring Integration will use `o.s.i.file.DefaultFileNameGenerator` if none is specified. `DefaultFileNameGenerator` will determine the file name
based on the value of the `file_name` header (if it exists) in the `MessageHeaders`, or if the payload of the `Message` is already a `java.io.File`, then it will
use the original name of that file.

== Options

The **$$ftp$$** $$sink$$ has the following options:

$$autoCreateDir$$:: $$remote directory must be auto created if it does not exist$$ *($$boolean$$, default: `true`)*
$$clientMode$$:: $$client mode to use: 2 for passive mode and 0 for active mode$$ *($$int$$, default: `0`)*
$$host$$:: $$the host name for the FTP server$$ *($$String$$, default: `localhost`)*
$$mode$$:: $$what to do if the file already exists$$ *($$Mode$$, default: `REPLACE`, possible values: `APPEND,REPLACE,FAIL,IGNORE`)*
$$password$$:: $$the password for the FTP connection$$ *($$Password$$, no default)*
$$port$$:: $$the port for the FTP server$$ *($$int$$, default: `21`)*
$$remoteDir$$:: $$the remote directory to transfer the files to$$ *($$String$$, default: `/`)*
$$remoteFileSeparator$$:: $$file separator to use on the remote side$$ *($$String$$, default: `/`)*
$$temporaryRemoteDir$$:: $$temporary remote directory that should be used$$ *($$String$$, default: `/`)*
$$tmpFileSuffix$$:: $$extension to use on server side when uploading files$$ *($$String$$, default: `.tmp`)*
$$useTemporaryFilename$$:: $$use a temporary filename while transferring the file and rename it to its final name once it's fully transferred$$ *($$boolean$$, default: `true`)*
$$username$$:: $$the username for the FTP connection$$ *($$String$$, no default)*

//end::ref-doc[]

== Build

```
$ mvn clean package
```

== Run

```
$ java -jar target/ftp-sink-${version}-exec.jar
```