sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
jdk:
  - oraclejdk8
services:
  - redis-server
install: true
#- ./mvnw install -P docs -q -U -DskipTests=true
#- ./docs/src/main/asciidoc/ghpages.sh
script:
  - ./mvnw -s .settings.xml package -nsu
