tag::ref-doc[]
= Splitter Processor
The splitter app builds upon the concept of the same name in Spring Integration and allows the splitting of a single
message into several distinct messages.

== Options
$$expression$$:: $$a SpEL expression which would typically evaluate to an array or collection$$ *($$String$$, default: `null`)*
$$delimiters$$:: $$A list of delimiters to tokenize a String payload ('expression' must be null)$$ *($$String$$, default: `null`)*
$$fileMarkers$$:: $$Split File payloads, when true, START and END marker messages will be emitted, when false no markers are emitted$$ *($$String$$, default: `null`)*
$$charset$$:: $$Split File payloads using this charset to convert bytes to String$$ *($$String$$, default: `null`)*
$$applySequence$$:: $$Add correlation and sequence information to the message headers$$ *($$String$$, default: `true`)*

When no `expression`, `fileMarkers`, or `charset` is provided, a `DefaultMessageSplitter` is configured with (optional) `delimiters`.
When `fileMarkers` or `charset` is provided, a `FileSplitter` is configured (you must provide either a `fileMarkers`
or `charset` to split files, which must be text-based - they are split into lines).
Otherwise, an `ExpressionEvaluatingMessageSplitter` is configured.

When splitting `File` payloads, the `sequenceSize` header is zero because the size cannot be determined at the beginning.

[CAUTION]
Ambiguous properties are not allowed.

== JSON Example

As part of the SpEL expression you can make use of the pre-registered JSON Path function. The syntax is
`#jsonPath(payload, '<json path expression>')`.

For example, consider the following JSON:

[source, json]
----
{ "store": {
    "book": [
        {
            "category": "reference",
            "author": "Nigel Rees",
            "title": "Sayings of the Century",
            "price": 8.95
        },
        {
            "category": "fiction",
            "author": "Evelyn Waugh",
            "title": "Sword of Honour",
            "price": 12.99
        },
        {
            "category": "fiction",
            "author": "Herman Melville",
            "title": "Moby Dick",
            "isbn": "0-553-21311-3",
            "price": 8.99
        },
        {
            "category": "fiction",
            "author": "J. R. R. Tolkien",
            "title": "The Lord of the Rings",
            "isbn": "0-395-19395-8",
            "price": 22.99
        }
    ],
    "bicycle": {
        "color": "red",
        "price": 19.95
    }
}}
----

and an expression `#jsonPath(payload, '$.store.book')`; the result will be 4 messages, each with a `Map` payload
containing the properties of a single book.

//end::ref-doc[]
== Building with Maven

```
$> mvn package
```

== Running the Application

```
$> java -jar target/splitter-processor-${version}-exec.jar
```
