= Spring Cloud Stream Trigger Source

This module sends trigger based on a fixed delay, date or cron expression. A payload which is evaluated using SpEL can
also be sent each time the trigger is triggered.

== Requirements

* Java 7 or Above

== Code Tour

TriggerSourceApplication:: the Spring Boot Main Application
TriggerSource:: configures the Inbound Channel Adapter bean
Trigger source re-uses the common trigger package `org.springframework.cloud.stream.module.trigger` for trigger
configuration, properties etc.,
Trigger source supports properties derived from TriggerProperties:
  * payload - a SpEL expression (default = '')
  * fixedDelay - fixed delay for the Periodic trigger
  * initialDelay - initial delay for the Periodic trigger
  * timeUnit - time unit to apply for delay (default = seconds)
  * date - the date value for the trigger
  * dateFormat - format for the date value
  * cron - the Cron expression for the Cron Trigger

== Build

```
$ mvn clean package
```

== Run

```
$ java -jar target/trigger-source-${version}-exec.jar
```
