= Spring Cloud Stream Counter Sink

A *Spring Cloud Stream* module that simply counts the number of messages it receives,
optionally storing counts in a separate store such as redis.
== Requirements

To run this module, you will need to have installed:

* Java 7 or Above
* One of the supported Spring Cloud Stream binders (_e.g._ redis, rabbit, _etc._)
* Redis to store counters (optional)

== Code Tour

CounterSinkApplication:: the Spring Boot Main Application
CounterSink:: the actual module code that interacts with message channels
CounterSinkProperties:: defines the configuration properties that are available to the Filter Processor
  * name: the name of the counter to increment
  * nameExpression: a SpEL expression used to derive the name of the counter to increment
  * store: where to store counters. This project's code supports `memory` and `redis`


## Building with Maven

Build the module by executing:

```
$> mvn package
```

## Running the Application

To start the module execute the following:
```
$> java -jar target/counter-sink-${version}-exec.jar
```