// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: error.proto

package org.cloudfoundry.dropsonde.events;

public final class ErrorFactory {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_events_Error_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_events_Error_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\013error.proto\022\006events\"6\n\005Error\022\016\n\006source" +
                        "\030\001 \002(\t\022\014\n\004code\030\002 \002(\005\022\017\n\007message\030\003 \002(\tB1\n" +
                        "!org.cloudfoundry.dropsonde.eventsB\014Erro" +
                        "rFactory"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_events_Error_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_events_Error_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_events_Error_descriptor,
                new java.lang.String[]{"Source", "Code", "Message",});
    }

    private ErrorFactory() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface ErrorOrBuilder extends
            // @@protoc_insertion_point(interface_extends:events.Error)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required string source = 1;</code>
         * <p>
         * <pre>
         * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
         * </pre>
         */
        boolean hasSource();

        /**
         * <code>required string source = 1;</code>
         * <p>
         * <pre>
         * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
         * </pre>
         */
        java.lang.String getSource();

        /**
         * <code>required string source = 1;</code>
         * <p>
         * <pre>
         * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
         * </pre>
         */
        com.google.protobuf.ByteString
        getSourceBytes();

        /**
         * <code>required int32 code = 2;</code>
         * <p>
         * <pre>
         * &#47; Numeric error code. This is provided for programmatic responses to the error.
         * </pre>
         */
        boolean hasCode();

        /**
         * <code>required int32 code = 2;</code>
         * <p>
         * <pre>
         * &#47; Numeric error code. This is provided for programmatic responses to the error.
         * </pre>
         */
        int getCode();

        /**
         * <code>required string message = 3;</code>
         * <p>
         * <pre>
         * &#47; Error description (preferably human-readable).
         * </pre>
         */
        boolean hasMessage();

        /**
         * <code>required string message = 3;</code>
         * <p>
         * <pre>
         * &#47; Error description (preferably human-readable).
         * </pre>
         */
        java.lang.String getMessage();

        /**
         * <code>required string message = 3;</code>
         * <p>
         * <pre>
         * &#47; Error description (preferably human-readable).
         * </pre>
         */
        com.google.protobuf.ByteString
        getMessageBytes();
    }

    /**
     * Protobuf type {@code events.Error}
     * <p>
     * <pre>
     * &#47; An Error event represents an error in the originating process.
     * </pre>
     */
    public static final class Error extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:events.Error)
            ErrorOrBuilder {
        public static final int SOURCE_FIELD_NUMBER = 1;
        public static final int CODE_FIELD_NUMBER = 2;
        public static final int MESSAGE_FIELD_NUMBER = 3;
        private static final Error defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<Error> PARSER =
                new com.google.protobuf.AbstractParser<Error>() {
                    public Error parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Error(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new Error(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private java.lang.Object source_;
        private int code_;
        private java.lang.Object message_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;
        // Use Error.newBuilder() to construct.
        private Error(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Error(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Error(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000001;
                            source_ = bs;
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            code_ = input.readInt32();
                            break;
                        }
                        case 26: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000004;
                            message_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static Error getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.cloudfoundry.dropsonde.events.ErrorFactory.internal_static_events_Error_descriptor;
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static org.cloudfoundry.dropsonde.events.ErrorFactory.Error parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(org.cloudfoundry.dropsonde.events.ErrorFactory.Error prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Error getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.cloudfoundry.dropsonde.events.ErrorFactory.internal_static_events_Error_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.cloudfoundry.dropsonde.events.ErrorFactory.Error.class, org.cloudfoundry.dropsonde.events.ErrorFactory.Error.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Error> getParserForType() {
            return PARSER;
        }

        /**
         * <code>required string source = 1;</code>
         * <p>
         * <pre>
         * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
         * </pre>
         */
        public boolean hasSource() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string source = 1;</code>
         * <p>
         * <pre>
         * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
         * </pre>
         */
        public java.lang.String getSource() {
            java.lang.Object ref = source_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    source_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string source = 1;</code>
         * <p>
         * <pre>
         * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
         * </pre>
         */
        public com.google.protobuf.ByteString
        getSourceBytes() {
            java.lang.Object ref = source_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                source_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>required int32 code = 2;</code>
         * <p>
         * <pre>
         * &#47; Numeric error code. This is provided for programmatic responses to the error.
         * </pre>
         */
        public boolean hasCode() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required int32 code = 2;</code>
         * <p>
         * <pre>
         * &#47; Numeric error code. This is provided for programmatic responses to the error.
         * </pre>
         */
        public int getCode() {
            return code_;
        }

        /**
         * <code>required string message = 3;</code>
         * <p>
         * <pre>
         * &#47; Error description (preferably human-readable).
         * </pre>
         */
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string message = 3;</code>
         * <p>
         * <pre>
         * &#47; Error description (preferably human-readable).
         * </pre>
         */
        public java.lang.String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    message_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string message = 3;</code>
         * <p>
         * <pre>
         * &#47; Error description (preferably human-readable).
         * </pre>
         */
        public com.google.protobuf.ByteString
        getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            source_ = "";
            code_ = 0;
            message_ = "";
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasSource()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMessage()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getSourceBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt32(2, code_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getMessageBytes());
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getSourceBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, code_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getMessageBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code events.Error}
         * <p>
         * <pre>
         * &#47; An Error event represents an error in the originating process.
         * </pre>
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:events.Error)
                org.cloudfoundry.dropsonde.events.ErrorFactory.ErrorOrBuilder {
            private int bitField0_;
            private java.lang.Object source_ = "";
            private int code_;
            private java.lang.Object message_ = "";

            // Construct using org.cloudfoundry.dropsonde.events.ErrorFactory.Error.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return org.cloudfoundry.dropsonde.events.ErrorFactory.internal_static_events_Error_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return org.cloudfoundry.dropsonde.events.ErrorFactory.internal_static_events_Error_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.cloudfoundry.dropsonde.events.ErrorFactory.Error.class, org.cloudfoundry.dropsonde.events.ErrorFactory.Error.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                source_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                code_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return org.cloudfoundry.dropsonde.events.ErrorFactory.internal_static_events_Error_descriptor;
            }

            public org.cloudfoundry.dropsonde.events.ErrorFactory.Error getDefaultInstanceForType() {
                return org.cloudfoundry.dropsonde.events.ErrorFactory.Error.getDefaultInstance();
            }

            public org.cloudfoundry.dropsonde.events.ErrorFactory.Error build() {
                org.cloudfoundry.dropsonde.events.ErrorFactory.Error result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public org.cloudfoundry.dropsonde.events.ErrorFactory.Error buildPartial() {
                org.cloudfoundry.dropsonde.events.ErrorFactory.Error result = new org.cloudfoundry.dropsonde.events.ErrorFactory.Error(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.source_ = source_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.code_ = code_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.cloudfoundry.dropsonde.events.ErrorFactory.Error) {
                    return mergeFrom((org.cloudfoundry.dropsonde.events.ErrorFactory.Error) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.cloudfoundry.dropsonde.events.ErrorFactory.Error other) {
                if (other == org.cloudfoundry.dropsonde.events.ErrorFactory.Error.getDefaultInstance()) return this;
                if (other.hasSource()) {
                    bitField0_ |= 0x00000001;
                    source_ = other.source_;
                    onChanged();
                }
                if (other.hasCode()) {
                    setCode(other.getCode());
                }
                if (other.hasMessage()) {
                    bitField0_ |= 0x00000004;
                    message_ = other.message_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasSource()) {

                    return false;
                }
                if (!hasCode()) {

                    return false;
                }
                if (!hasMessage()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.cloudfoundry.dropsonde.events.ErrorFactory.Error parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.cloudfoundry.dropsonde.events.ErrorFactory.Error) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>required string source = 1;</code>
             * <p>
             * <pre>
             * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
             * </pre>
             */
            public boolean hasSource() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string source = 1;</code>
             * <p>
             * <pre>
             * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
             * </pre>
             */
            public java.lang.String getSource() {
                java.lang.Object ref = source_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        source_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string source = 1;</code>
             * <p>
             * <pre>
             * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
             * </pre>
             */
            public Builder setSource(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                source_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string source = 1;</code>
             * <p>
             * <pre>
             * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
             * </pre>
             */
            public com.google.protobuf.ByteString
            getSourceBytes() {
                java.lang.Object ref = source_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    source_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string source = 1;</code>
             * <p>
             * <pre>
             * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
             * </pre>
             */
            public Builder setSourceBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                source_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string source = 1;</code>
             * <p>
             * <pre>
             * &#47; Source of the error. This may or may not be the same as the Origin in the envelope.
             * </pre>
             */
            public Builder clearSource() {
                bitField0_ = (bitField0_ & ~0x00000001);
                source_ = getDefaultInstance().getSource();
                onChanged();
                return this;
            }

            /**
             * <code>required int32 code = 2;</code>
             * <p>
             * <pre>
             * &#47; Numeric error code. This is provided for programmatic responses to the error.
             * </pre>
             */
            public boolean hasCode() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required int32 code = 2;</code>
             * <p>
             * <pre>
             * &#47; Numeric error code. This is provided for programmatic responses to the error.
             * </pre>
             */
            public int getCode() {
                return code_;
            }

            /**
             * <code>required int32 code = 2;</code>
             * <p>
             * <pre>
             * &#47; Numeric error code. This is provided for programmatic responses to the error.
             * </pre>
             */
            public Builder setCode(int value) {
                bitField0_ |= 0x00000002;
                code_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 code = 2;</code>
             * <p>
             * <pre>
             * &#47; Numeric error code. This is provided for programmatic responses to the error.
             * </pre>
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000002);
                code_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>required string message = 3;</code>
             * <p>
             * <pre>
             * &#47; Error description (preferably human-readable).
             * </pre>
             */
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string message = 3;</code>
             * <p>
             * <pre>
             * &#47; Error description (preferably human-readable).
             * </pre>
             */
            public java.lang.String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        message_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string message = 3;</code>
             * <p>
             * <pre>
             * &#47; Error description (preferably human-readable).
             * </pre>
             */
            public Builder setMessage(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string message = 3;</code>
             * <p>
             * <pre>
             * &#47; Error description (preferably human-readable).
             * </pre>
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                java.lang.Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string message = 3;</code>
             * <p>
             * <pre>
             * &#47; Error description (preferably human-readable).
             * </pre>
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string message = 3;</code>
             * <p>
             * <pre>
             * &#47; Error description (preferably human-readable).
             * </pre>
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000004);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:events.Error)
        }

        // @@protoc_insertion_point(class_scope:events.Error)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
