//tag::ref-doc[]
= RabbitMQ Source

The "rabbit" source enables receiving messages from RabbitMQ.

The queue(s) must exist before the stream is deployed; they are not created automatically.
You can easily create a Queue using the RabbitMQ web UI.

== Options

The **$$rabbit$$** $$source$$ has the following options:

$$enableRetry$$:: $$enable retry; when retries are exhausted the message will be rejected; message disposition will depend on dead letter configuration$$ *($$boolean$$, default: `false`)*
$$initialRetryInterval$$:: $$initial interval between retries$$ *($$int$$, default: `1000`)*
$$mappedRequestHeaders$$:: $$request message header names to be mapped from the incoming message$$ *($$String$$, default: `STANDARD_REQUEST_HEADERS`)*
$$maxAttempts$$:: $$maximum delivery attempts$$ *($$int$$, default: `3`)*
$$maxConcurrency$$:: $$the maximum number of consumers$$ *($$int$$, default: `1`)*
$$maxRetryInterval$$:: $$maximum retry interval$$ *($$int$$, default: `30000`)*
$$queues$$:: $$the queue(s) from which messages will be received$$ *($$String$$, default: no default)*
$$requeue$$:: $$whether rejected messages will be requeued by default$$ *($$boolean$$, default: `true`)*
$$retryMultiplier$$:: $$retry interval multiplier$$ *($$double$$, default: `2.0`)*
$$transacted$$:: $$true if the channel is to be transacted$$ *($$boolean$$, default: `false`)*

Also see the http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[Spring Boot Documentation]
for addition properties for the broker connections and listener properties.

[[rabbitSourceRetry]]
=== A Note About Retry
NOTE: With the default _ackMode_ (*AUTO*) and _requeue_ (*true*) options, failed message deliveries will be retried
indefinitely.
Since there is not much processing in the rabbit source, the risk of failure in the source itself is small, unless
the downstream `Binder` is not connected for some reason.
Setting _requeue_ to *false* will cause messages to be rejected on the first attempt (and possibly sent to a Dead Letter
Exchange/Queue if the broker is so configured).
The _enableRetry_ option allows configuration of retry parameters such that a failed message delivery can be retried and
eventually discarded (or dead-lettered) when retries are exhausted.
The delivery thread is suspended during the retry interval(s).
Retry options are _enableRetry_, _maxAttempts_, _initialRetryInterval_, _retryMultiplier_, and _maxRetryInterval_.
Message deliveries failing with a _MessageConversionException_ are never retried; the assumption being that if a message
could not be converted on the first attempt, subsequent attempts will also fail.
Such messages are discarded (or dead-lettered).

//end::ref-doc[]
== Build

```
$> mvn package
```

== Run

```
$> java -jar target/rabbit-source-${version}-exec.jar
```
